/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    ChatBubble: typeof import('./../src/components/ChatBubble.vue')['default']
    CloudUploadOutlined: typeof import('@ant-design/icons-vue')['CloudUploadOutlined']
    CommentOutlined: typeof import('@ant-design/icons-vue')['CommentOutlined']
    DeleteOutlined: typeof import('@ant-design/icons-vue')['DeleteOutlined']
    EyeOutlined: typeof import('@ant-design/icons-vue')['EyeOutlined']
    LinkOutlined: typeof import('@ant-design/icons-vue')['LinkOutlined']
    LoadingOutlined: typeof import('@ant-design/icons-vue')['LoadingOutlined']
    MdPreview: typeof import('./../src/components/MdPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SenderInput: typeof import('./../src/components/SenderInput.vue')['default']
    WelcomeIndex: typeof import('./../src/components/WelcomeIndex.vue')['default']
  }
}
